name: Conventional Commits

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
